import { faBars, faRotateRight, faXmark } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { useCallback, useEffect, useRef, useState } from 'react';
import { type GermanLevel, GermanLevelSelector } from './components/GermanLevelSelector';
import { PassageWriter } from './components/PassageWriter';
import { ThemeSelector } from './components/ThemeSelector';
import type { Passage } from './data/passages';
import { createPassageFromGenerated } from './data/passages';
import { generateGermanText } from './services/openrouter';
import './App.css';

const STRICT_MODE_STORAGE_KEY = 'learn-by-typing-strict-mode';
const GERMAN_LEVEL_STORAGE_KEY = 'learn-by-typing-german-level';
const COOLDOWN_SECONDS = 10;

function getInitialStrictMode(): boolean {
  try {
    const stored = localStorage.getItem(STRICT_MODE_STORAGE_KEY);
    if (stored === 'false') {
      return false;
    }
  } catch {
    // localStorage unavailable (incognito, disabled, etc.)
  }
  return true;
}

function getInitialGermanLevel(): GermanLevel {
  try {
    const stored = localStorage.getItem(GERMAN_LEVEL_STORAGE_KEY);
    if (stored && ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'].includes(stored)) {
      return stored as GermanLevel;
    }
  } catch {
    // localStorage unavailable
  }
  return 'A1';
}

function App() {
  const [activePassage, setActivePassage] = useState<Passage | null>(null);
  const [strict, setStrict] = useState<boolean>(() => getInitialStrictMode());
  const [showWordGloss, setShowWordGloss] = useState<boolean>(false);
  const [sidebarOpen, setSidebarOpen] = useState<boolean>(false);
  const [germanLevel, setGermanLevel] = useState<GermanLevel>(() => getInitialGermanLevel());
  const [isLoading, setIsLoading] = useState(true);
  const [cooldownEnd, setCooldownEnd] = useState<number | null>(null);
  const [generationError, setGenerationError] = useState<string | null>(null);
  const hasAutoGeneratedRef = useRef(false);

  const handleGenerateText = useCallback(
    async (level: GermanLevel, isInitial = false) => {
      if (!isInitial && isLoading) return;
      if (!isInitial && cooldownEnd !== null && Date.now() < cooldownEnd) return;

      setIsLoading(true);
      setGenerationError(null);

      try {
        const generated = await generateGermanText(level);
        const newPassage = createPassageFromGenerated(generated, level);
        setActivePassage(newPassage);
        setCooldownEnd(Date.now() + COOLDOWN_SECONDS * 1000);
      } catch (error) {
        let message = isInitial
          ? 'Failed to load text. Please check your connection and try again.'
          : 'Failed to generate new text. Please try again.';

        if (error instanceof Error) {
          if (error.message.includes('429')) {
            message =
              'Rate limit reached. Free tier allows 20 requests/day (200 with credits). Please wait.';
          } else if (error.message.includes('401')) {
            message = 'Invalid API key. Please check your OpenRouter API key.';
          } else if (error.message.includes('fetch')) {
            message = 'Network error. Please check your internet connection.';
          }
        }

        setGenerationError(message);
      } finally {
        setIsLoading(false);
      }
    },
    [cooldownEnd, isLoading],
  );

  useEffect(() => {
    try {
      localStorage.setItem(STRICT_MODE_STORAGE_KEY, String(strict));
    } catch {
      // localStorage unavailable
    }
  }, [strict]);

  useEffect(() => {
    try {
      localStorage.setItem(GERMAN_LEVEL_STORAGE_KEY, germanLevel);
    } catch {
      // localStorage unavailable
    }
  }, [germanLevel]);

  // Auto-generate on mount with A1
  useEffect(() => {
    if (hasAutoGeneratedRef.current) return;
    hasAutoGeneratedRef.current = true;
    handleGenerateText('A1', true);
  }, [handleGenerateText]);

  // Update cooldown timer
  useEffect(() => {
    if (!cooldownEnd) return;

    const interval = setInterval(() => {
      if (Date.now() >= cooldownEnd) {
        setCooldownEnd(null);
      }
    }, 1000);

    return () => clearInterval(interval);
  }, [cooldownEnd]);

  const getRemainingCooldown = () => {
    if (!cooldownEnd) return 0;
    const remaining = Math.ceil((cooldownEnd - Date.now()) / 1000);
    return Math.max(0, remaining);
  };

  const isInCooldown = () => {
    return cooldownEnd !== null && Date.now() < cooldownEnd;
  };

  const handleLevelChange = (level: GermanLevel) => {
    setGermanLevel(level);
    handleGenerateText(level);
  };

  return (
    <div className="app-container">
      <aside className={`sidebar ${sidebarOpen ? 'open' : ''}`}>
        <div className="sidebar-header">
          <h2>Settings</h2>
          <button
            type="button"
            className="sidebar-close"
            onClick={() => setSidebarOpen(false)}
            aria-label="Close sidebar"
          >
            <FontAwesomeIcon icon={faXmark} />
          </button>
        </div>
        <div className="sidebar-content">
          <div className="setting-group">
            <h3>Learning</h3>
            <GermanLevelSelector value={germanLevel} onChange={handleLevelChange} />
            <p className="setting-description">
              Select your German proficiency level (CEFR). This will be used for AI-generated texts.
            </p>
          </div>

          <div className="setting-group">
            <h3>Typing Mode</h3>
            <label className="setting-toggle">
              <input
                type="checkbox"
                checked={strict}
                onChange={(e) => setStrict(e.target.checked)}
              />
              <span className="toggle-switch"></span>
              <span className="setting-label">Strict Mode</span>
            </label>
            <p className="setting-description">
              {strict
                ? 'You must type the correct character to proceed.'
                : 'Mistakes are recorded but you can continue.'}
            </p>
          </div>

          <div className="setting-group">
            <h3>Display</h3>
            <label className="setting-toggle">
              <input
                type="checkbox"
                checked={showWordGloss}
                onChange={(e) => setShowWordGloss(e.target.checked)}
              />
              <span className="toggle-switch"></span>
              <span className="setting-label">Show Word Gloss</span>
            </label>
            <p className="setting-description">
              {showWordGloss
                ? 'Single-word translations are visible under each word.'
                : 'Single-word translations are hidden.'}
            </p>
          </div>

          <div className="setting-group">
            <h3>Theme</h3>
            <ThemeSelector />
          </div>
        </div>
      </aside>

      {sidebarOpen && (
        <button
          type="button"
          className="sidebar-overlay"
          onMouseDown={(e) => e.preventDefault()}
          onClick={() => setSidebarOpen(false)}
          aria-label="Close settings"
        />
      )}

      <div className="app">
        <button
          type="button"
          className="sidebar-toggle"
          onClick={() => setSidebarOpen(true)}
          aria-label="Open settings"
        >
          <FontAwesomeIcon icon={faBars} />
        </button>

        <header className="header">
          <h1>Learn by Typing</h1>
          <div className="controls">
            <GermanLevelSelector value={germanLevel} onChange={handleLevelChange} />
            <button
              type="button"
              onClick={() => handleGenerateText(germanLevel)}
              disabled={isLoading || isInCooldown()}
              className={`restart-btn ${isLoading || isInCooldown() ? 'disabled' : ''}`}
              aria-label={
                isLoading
                  ? 'Generating...'
                  : isInCooldown()
                    ? `Wait ${getRemainingCooldown()}s`
                    : 'Generate new text'
              }
              title={
                isInCooldown()
                  ? `Cooldown: ${getRemainingCooldown()}s remaining`
                  : 'Generate new text'
              }
            >
              {isLoading ? (
                <span className="spinner" />
              ) : isInCooldown() ? (
                `${getRemainingCooldown()}s`
              ) : (
                <FontAwesomeIcon icon={faRotateRight} />
              )}
            </button>
          </div>
        </header>

        <main className="main-content">
          {isLoading ? (
            <div className="loading-container">
              <div className="spinner-large" />
              <p>Generating text...</p>
            </div>
          ) : generationError ? (
            <div className="error-container">
              <p>{generationError}</p>
              <button
                type="button"
                onClick={() => handleGenerateText(germanLevel)}
                className="retry-btn"
              >
                Retry
              </button>
            </div>
          ) : activePassage ? (
            <PassageWriter
              key={activePassage.id}
              passage={activePassage}
              strict={strict}
              showWordGloss={showWordGloss}
              sidebarOpen={sidebarOpen}
            />
          ) : null}
        </main>

        <footer className="footer">
          <p>Click anywhere to focus. Type the German text on the left.</p>
        </footer>
      </div>
    </div>
  );
}

export default App;
