import { faCog, faEye, faEyeSlash, faRotateRight } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { OpenRouterError } from '@openrouter/sdk/models/errors';
import { type ReactNode, useCallback, useEffect, useRef, useState } from 'react';
import { type GermanLevel, GermanLevelSelector } from './components/GermanLevelSelector';
import { PassageWriter } from './components/PassageWriter';
import { ThemeSelector } from './components/ThemeSelector';
import { getRandomMockPassage } from './data/mockPassages';
import type { Passage } from './data/passages';
import { createPassageFromGenerated } from './data/passages';
import { generateGermanText } from './services/openrouter';
import './App.css';

const STRICT_MODE_STORAGE_KEY = 'learn-by-typing-strict-mode';
const GERMAN_LEVEL_STORAGE_KEY = 'learn-by-typing-german-level';
const API_KEY_STORAGE_KEY = 'learn-by-typing-api-key';
const COOLDOWN_SECONDS = 10;

function getInitialStrictMode(): boolean {
  try {
    const stored = localStorage.getItem(STRICT_MODE_STORAGE_KEY);
    if (stored === 'false') {
      return false;
    }
  } catch {
    // localStorage unavailable (incognito, disabled, etc.)
  }
  return true;
}

function getInitialGermanLevel(): GermanLevel {
  try {
    const stored = localStorage.getItem(GERMAN_LEVEL_STORAGE_KEY);
    if (stored && ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'].includes(stored)) {
      return stored as GermanLevel;
    }
  } catch {
    // localStorage unavailable
  }
  return 'A1';
}

function getInitialApiKey(): string {
  try {
    const stored = localStorage.getItem(API_KEY_STORAGE_KEY);
    if (stored) return stored;
  } catch {
    // localStorage unavailable
  }
  return (import.meta.env.VITE_OPENROUTER_API_KEY as string) ?? '';
}

function App() {
  const [activePassage, setActivePassage] = useState<Passage | null>(null);
  const [strict, setStrict] = useState<boolean>(() => getInitialStrictMode());
  const [showWordGloss, setShowWordGloss] = useState<boolean>(false);
  const [view, setView] = useState<'main' | 'settings'>('main');
  const [germanLevel, setGermanLevel] = useState<GermanLevel>(() => getInitialGermanLevel());
  const [isLoading, setIsLoading] = useState(true);
  const [cooldownEnd, setCooldownEnd] = useState<number | null>(null);
  const [remainingSeconds, setRemainingSeconds] = useState(0);
  const [generationError, setGenerationError] = useState<ReactNode>(null);
  const [isMockText, setIsMockText] = useState(false);
  const [apiKey, setApiKey] = useState<string>(() => getInitialApiKey());
  const [showApiKey, setShowApiKey] = useState(false);
  const hasAutoGeneratedRef = useRef(false);

  const handleGenerateText = useCallback(
    async (level: GermanLevel, isInitial = false) => {
      if (!isInitial && isLoading) return;
      if (!isInitial && remainingSeconds > 0) return;

      setIsLoading(true);
      setGenerationError(null);

      try {
        const generated = await generateGermanText(level, apiKey);
        const newPassage = createPassageFromGenerated(generated, level);
        setActivePassage(newPassage);
        setIsMockText(generated.isMock === true);
        setCooldownEnd(Date.now() + COOLDOWN_SECONDS * 1000);
      } catch (error) {
        let message: ReactNode = isInitial
          ? 'Failed to load text. Please check your connection and try again.'
          : 'Failed to generate new text. Please try again.';

        if (error instanceof OpenRouterError) {
          if (error.statusCode === 429) {
            message =
              'Rate limit reached. Free tier allows 20 requests/day (200 with credits). Please wait.';
          } else if (error.statusCode === 401) {
            message = (
              <>
                Invalid API key.{' '}
                <a href="https://openrouter.ai/keys" target="_blank" rel="noopener noreferrer">
                  Get one at openrouter.ai/keys
                </a>
                .
              </>
            );
          }
        } else if (error instanceof Error && error.message.includes('fetch')) {
          message = 'Network error. Please check your internet connection.';
        }

        setGenerationError(message);
      } finally {
        setIsLoading(false);
      }
    },
    [remainingSeconds, isLoading, apiKey],
  );

  const handleUseMockText = useCallback(() => {
    const mock = getRandomMockPassage();
    const newPassage = createPassageFromGenerated(mock, germanLevel);
    setActivePassage(newPassage);
    setIsMockText(true);
    setGenerationError(null);
    setCooldownEnd(Date.now() + COOLDOWN_SECONDS * 1000);
  }, [germanLevel]);

  useEffect(() => {
    try {
      localStorage.setItem(STRICT_MODE_STORAGE_KEY, String(strict));
    } catch {
      // localStorage unavailable
    }
  }, [strict]);

  useEffect(() => {
    try {
      localStorage.setItem(GERMAN_LEVEL_STORAGE_KEY, germanLevel);
    } catch {
      // localStorage unavailable
    }
  }, [germanLevel]);

  useEffect(() => {
    try {
      localStorage.setItem(API_KEY_STORAGE_KEY, apiKey);
    } catch {
      // localStorage unavailable
    }
  }, [apiKey]);

  // Auto-generate on mount
  useEffect(() => {
    if (hasAutoGeneratedRef.current) return;
    hasAutoGeneratedRef.current = true;
    if (!apiKey) {
      setView('settings');
      setIsLoading(false);
      return;
    }
    handleGenerateText(germanLevel, true);
  }, [handleGenerateText, apiKey, germanLevel]);

  // Update document title when passage changes
  useEffect(() => {
    if (activePassage) {
      document.title = `${activePassage.title} — German Typing Practice`;
    }
  }, [activePassage]);

  // Keyboard shortcuts: Ctrl+Enter to generate, Escape to close settings
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') {
        if (view === 'main' && !isLoading && remainingSeconds === 0) {
          handleGenerateText(germanLevel);
        }
      } else if (e.key === 'Escape') {
        setView('main');
      }
    };
    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, [handleGenerateText, germanLevel, isLoading, remainingSeconds, view]);

  // Update cooldown timer
  useEffect(() => {
    if (!cooldownEnd) {
      setRemainingSeconds(0);
      return;
    }

    const tick = () => {
      const remaining = Math.max(0, Math.ceil((cooldownEnd - Date.now()) / 1000));
      setRemainingSeconds(remaining);
      if (remaining === 0) setCooldownEnd(null);
    };

    tick();
    const interval = setInterval(tick, 1000);
    return () => clearInterval(interval);
  }, [cooldownEnd]);

  const isInCooldown = () => remainingSeconds > 0;

  const handleLevelChange = (level: GermanLevel) => {
    setGermanLevel(level);
    handleGenerateText(level);
  };

  const apiKeyValid = apiKey.startsWith('sk-or-');
  const apiKeyInvalid = apiKey.length > 0 && !apiKeyValid;

  if (view === 'settings') {
    return (
      <div className="app-container">
        <div className="app settings-page">
          <div className="settings-page-header">
            <button
              type="button"
              className="settings-back-btn"
              onClick={() => setView('main')}
              aria-label="Back to main"
            >
              ← Back
            </button>
            <h2>Settings</h2>
          </div>

          <div className="settings-page-content">
            <div className="settings-section">
              <h3>API Configuration</h3>
              <div className="api-key-wrapper">
                <input
                  type={showApiKey ? 'text' : 'password'}
                  className={`api-key-input ${apiKeyValid ? 'api-key-valid' : ''} ${apiKeyInvalid ? 'api-key-invalid' : ''}`}
                  value={apiKey}
                  onChange={(e) => setApiKey(e.target.value)}
                  placeholder="sk-or-v1-..."
                  spellCheck={false}
                  autoComplete="off"
                />
                <button
                  type="button"
                  className="api-key-eye-btn"
                  onClick={() => setShowApiKey((v) => !v)}
                  aria-label={showApiKey ? 'Hide API key' : 'Show API key'}
                >
                  <FontAwesomeIcon icon={showApiKey ? faEyeSlash : faEye} />
                </button>
                {apiKeyValid && <span className="api-key-status valid">✓</span>}
                {apiKeyInvalid && <span className="api-key-status invalid">✗</span>}
              </div>
              <p className="api-key-hint">
                Get a free key at{' '}
                <a href="https://openrouter.ai/keys" target="_blank" rel="noopener noreferrer">
                  openrouter.ai/keys
                </a>
              </p>
            </div>

            <div className="settings-section">
              <h3>Learning</h3>
              <GermanLevelSelector
                value={germanLevel}
                onChange={(level) => setGermanLevel(level)}
                disabled={false}
              />
              <p className="setting-description">
                Select your German proficiency level (CEFR). This will be used for AI-generated
                texts.
              </p>
            </div>

            <div className="settings-section">
              <h3>Typing</h3>
              <label className="setting-toggle">
                <input
                  type="checkbox"
                  checked={strict}
                  onChange={(e) => setStrict(e.target.checked)}
                />
                <span className="toggle-switch"></span>
                <span className="setting-label">Strict Mode</span>
              </label>
              <p className="setting-description">
                {strict
                  ? 'You must type the correct character to proceed.'
                  : 'Mistakes are recorded but you can continue.'}
              </p>
            </div>

            <div className="settings-section">
              <h3>Display</h3>
              <label className="setting-toggle">
                <input
                  type="checkbox"
                  checked={showWordGloss}
                  onChange={(e) => setShowWordGloss(e.target.checked)}
                />
                <span className="toggle-switch"></span>
                <span className="setting-label">Show Word Gloss</span>
              </label>
              <p className="setting-description">
                {showWordGloss
                  ? 'Single-word translations are visible under each word.'
                  : 'Single-word translations are hidden.'}
              </p>
            </div>

            <div className="settings-section">
              <h3>Theme</h3>
              <ThemeSelector />
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="app-container">
      <div className="app">
        <button
          type="button"
          className="settings-toggle"
          onClick={() => setView('settings')}
          aria-label="Open settings"
        >
          <FontAwesomeIcon icon={faCog} />
        </button>

        <header className="header">
          <h1>Learn by Typing</h1>
          <div className="controls">
            <GermanLevelSelector
              value={germanLevel}
              onChange={handleLevelChange}
              disabled={isLoading}
            />
            <button
              type="button"
              onClick={() => handleGenerateText(germanLevel)}
              disabled={isLoading || isInCooldown()}
              className={`restart-btn ${isLoading || isInCooldown() ? 'disabled' : ''}`}
              aria-label={
                isLoading
                  ? 'Generating...'
                  : isInCooldown()
                    ? `Wait ${remainingSeconds}s`
                    : 'Generate new text'
              }
              title={
                isInCooldown() ? `Cooldown: ${remainingSeconds}s remaining` : 'Generate new text'
              }
            >
              {isLoading ? (
                <span className="spinner" />
              ) : isInCooldown() ? (
                `${remainingSeconds}s`
              ) : (
                <FontAwesomeIcon icon={faRotateRight} />
              )}
            </button>
          </div>
        </header>

        <main className="main-content">
          {!apiKey ? (
            <div className="no-api-key-prompt">
              <p>No API key configured.</p>
              <button type="button" className="retry-btn" onClick={() => setView('settings')}>
                Open Settings
              </button>
            </div>
          ) : isLoading ? (
            <div className="loading-container">
              <div className="spinner-large" />
              <p>Generating text...</p>
            </div>
          ) : generationError ? (
            <div className="error-container">
              <p>{generationError}</p>
              <div className="error-actions">
                <button
                  type="button"
                  onClick={() => handleGenerateText(germanLevel)}
                  className="retry-btn"
                >
                  Retry
                </button>
                <button type="button" onClick={handleUseMockText} className="mock-btn">
                  Use example text
                </button>
              </div>
            </div>
          ) : activePassage ? (
            <>
              {isMockText && (
                <p className="mock-text-notice">Using example text (API unavailable)</p>
              )}
              <PassageWriter
                key={activePassage.id}
                passage={activePassage}
                strict={strict}
                showWordGloss={showWordGloss}
                sidebarOpen={false}
              />
            </>
          ) : null}
        </main>

        <footer className="footer">
          <p>Click anywhere to focus. Type the German text on the left.</p>
        </footer>
      </div>
    </div>
  );
}

export default App;
