#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$current_branch" = "main" ]; then
  echo "Error: direct pushes to main are blocked. Please use a PR." >&2
  exit 1
fi
